// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYL-O_wvdZhHrhWxm_VxUu-phqXo-mODI',
    appId: '1:64835867198:web:9f744342c12a1c0193f76f',
    messagingSenderId: '64835867198',
    projectId: 'flutterauth-6ac0b',
    authDomain: 'flutterauth-6ac0b.firebaseapp.com',
    storageBucket: 'flutterauth-6ac0b.appspot.com',
    measurementId: 'G-T3BWTTQGP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5JvaOhY6NKUvzU9rsj8gjeyXAD_DwsYM',
    appId: '1:64835867198:android:65f127192b2cfd3d93f76f',
    messagingSenderId: '64835867198',
    projectId: 'flutterauth-6ac0b',
    storageBucket: 'flutterauth-6ac0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBonO-4Iis7g1EY_W-UaC6sAIl0fQZcaY',
    appId: '1:64835867198:ios:f0616797fb3fbe8c93f76f',
    messagingSenderId: '64835867198',
    projectId: 'flutterauth-6ac0b',
    storageBucket: 'flutterauth-6ac0b.appspot.com',
    iosBundleId: 'com.example.onboradingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBonO-4Iis7g1EY_W-UaC6sAIl0fQZcaY',
    appId: '1:64835867198:ios:78a1c12c21974b9d93f76f',
    messagingSenderId: '64835867198',
    projectId: 'flutterauth-6ac0b',
    storageBucket: 'flutterauth-6ac0b.appspot.com',
    iosBundleId: 'com.example.onboradingScreen.RunnerTests',
  );
}
